adding support for Cloud WAN Appliance mode in attachment
aws-ia/terraform-aws-vpc pull request #100
Opened 2023-03-01 10:58 UTC by pablo19sc

2023-03-01 11:38 UTC, pablo19sc commented
![imgonline-com-ua-twotoone-E57ufDY1ba8S](https://user-images.githubusercontent.com/76947510/222128816-eb1cf620-cc08-4498-a14a-aa125e23cc9c.png)

2023-03-01 17:30 UTC, drewmullen submitted a review, later dismissed
LGTM!

2023-03-09 21:32 UTC, tlindsay42 requested changes
The terraform-docs lint test is failing because you need to update the examples:

```
$ git status
On branch pr100
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../cloud_wan/README.md
        modified:   ../public_private_flow_logs/README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

Also of note, the transit gateway example doesn't have documentation.

2023-03-27 19:55 UTC, andrew-glenn approved these changes

2023-03-27 21:08 UTC, merged