flow logs default update & required_provider 1.3.0
aws-ia/terraform-aws-vpc pull request #90
Opened 2022-10-05 09:51 UTC by pablo19sc

- Removed "experiments" block and update required_provider to >= 1.3.0 in all the provider definition (main providers.tf, submodules, and examples).
- Updated VPC Flow Logs variable definition to make use of the new "optional" functionality for object type.
- Minor changes in "flow logs" submodule (typo in one variable), in README.md (to add the proper link to 3.0 changes), and examples.

As some changes were done to the code, I attach here the result of different tests - the first one is the example of the flow logs piece (which is the main change in this PR).

![flowlog_test](https://user-images.githubusercontent.com/76947510/194032734-b6aa26c4-6742-4b6d-a575-614a1cbece46.png)
![transit_gateway_test](https://user-images.githubusercontent.com/76947510/194032724-9ee49eba-970e-4715-a7aa-db58df10aa23.png)
![secondary_cidr_test](https://user-images.githubusercontent.com/76947510/194032730-00c5e860-4123-4299-9b3f-86075f74192c.png)
![natgw_route_test](https://user-images.githubusercontent.com/76947510/194032732-bf30b89b-c562-4df7-9be8-a08ce00dc706.png)

2022-10-05 10:45 UTC, drewmullen commented on .header.md
> +_Note: For information regarding the 3.0 upgrade see our [upgrade guide](https://github.com/aws-ia/terraform-aws-vpc/blob/main/UPGRADE-GUIDE-3.0.md)._
THANK YOU FOR DOING THIS!

2022-10-05 10:49 UTC, drewmullen requested changes

2022-10-05 10:49 UTC, drewmullen commented on main.tf
> +  # flow_log_definition = local.flow_logs_definition
please remove these 2 unnecessary comments

2022-10-05 10:49 UTC, drewmullen commented on variables.tf
> +    log_destination_type = "cloud-watch-logs"
By default we probably do not want to build flow logs since they can get quite expensive

2022-10-05 10:49 UTC, drewmullen commented on examples/ipam/main.tf
> -  source  = "aws-ia/vpc/aws"
for each example, can you flip it back from `source = "../.." to the module source in tf regstiry

2022-10-20 10:19 UTC, pablo19sc commented
`terraform validate` in all the examples (showing validation passes)

<img width="425" alt="Screenshot 2022-10-20 at 12 15 43" src="https://user-images.githubusercontent.com/76947510/196922994-1f86ec35-a687-4551-8151-7ea82e41f1bd.png">
<img width="349" alt="Screenshot 2022-10-20 at 12 14 52" src="https://user-images.githubusercontent.com/76947510/196923000-9d95f4bb-1946-4758-9626-c69275de575c.png">
<img width="484" alt="Screenshot 2022-10-20 at 12 10 10" src="https://user-images.githubusercontent.com/76947510/196923001-067e4e1b-b356-4484-b4c5-8ff0ecc34445.png">
<img width="415" alt="Screenshot 2022-10-20 at 12 09 24" src="https://user-images.githubusercontent.com/76947510/196923003-fc313f2c-587f-4e91-ac3e-930791046b36.png">

2022-10-20 12:38 UTC, merged