Adding Cloud WAN support
aws-ia/terraform-aws-vpc pull request #92
Opened 2022-10-23 12:12 UTC by pablo19sc

Adding Cloud WAN support:

* Creation of core_network subnets.
* Creation of Core Network's VPC attachment.
* Support for attachment acceptance for VPC attachments.

2022-10-24 15:42 UTC, pablo19sc commented
Test of new example (cloud_wan)

![test_cloud_wan](https://user-images.githubusercontent.com/76947510/197567984-42b9c966-549f-4675-90b9-77da0631ce26.png)

2022-11-13 19:43 UTC, drewmullen requested changes
beautiful work. only 1 request here - lmk what you think

2022-11-13 19:43 UTC, drewmullen commented on .header.md
> +There are 3 reserved keys for subnet key names in var.subnets corresponding to types "public", "transit_gateway", and "core_network". Other custom subnet key names are valid are and those subnets wil
```suggestion
There are 3 reserved keys for subnet key names in var.subnets corresponding to types "public", "transit_gateway", and "core_network" [(a NetworkManager CloudWAN feature)](https://docs.aws.amazon.com/vpc/latest/cloudwan/cloudwan-networks-working-with.html). Other custom subnet key names are valid are and those subnets will be private subnets.
```

2022-11-13 19:44 UTC, drewmullen commented on .header.md
> +There are 3 reserved keys for subnet key names in var.subnets corresponding to types "public", "transit_gateway", and "core_network". Other custom subnet key names are valid are and those subnets wil
my thought here is that _most people_ dont know cloudwan but the term "core network" feels very confusing.

2022-11-14 18:48 UTC, drewmullen approved these changes
LGTM

2022-11-14 18:48 UTC, merged